# Site settings
title: GOV.AU
description: > # this means to ignore newlines until "baseurl:"
  Gov.au homepage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'ld_library_path/libreadline.so.5']
gems:
  - jekyll-assets

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"

prose:
  rooturl: '_includes/content'
  siteurl: 'http://gov-au.cfapps.io'
  ignore:
    - _config.yml
    - /_assets
    - /_data
    - /_layouts
    - /assets
    - /bin
    - /fonts
    - /_posts

assets:
  compress:
    css: true
    js: true
  cache: .asset-cache
  prefix: "/cdn"
  digest: true
