# Site settings
title: GOV.AU
description: This GOV.AU prototype is an example of how joined up government services could look and work for users.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: none
url: "https://alpha.gov.au" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ['config.ru', 'README.markdown', 'Procfile', 'Gemfile', 'Gemfile.lock', 'ld_library_path/libreadline.so.5']
gems:
  - jekyll-assets

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"

prose:
  rooturl: '_includes/content'
  siteurl: 'https://alpha.gov.au'
  ignore:
    - _config.yml
    - /_assets
    - /_data
    - /_layouts
    - /assets
    - /bin
    - /fonts
    - /_posts

assets:
  compress:
    css: true
    js: true
  cache: .asset-cache
  prefix: "/cdn"
  digest: true
