# Site settings
title: GOV.AU
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'ld_library_path/libreadline.so.5']

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"

prose:
  rooturl: '_includes/content'
  siteurl: 'http://gov-au.cfapps.io'
  ignore:
    - _config.yml
    - /_data
    - /_layouts
    - /_sass
    - /assets
    - /bin
    - /css
    - /js
    - /_posts
